

# Hibernate Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3356/test
    username: root
    password: my-secret-pw

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: create